services:
  postgres:
    image: postgres:16
    container_name: anchorfy_ct
    restart: always
    environment:
      POSTGRES_USER: anchorfy
      POSTGRES_PASSWORD: anchorfy
      POSTGRES_DB: anchorfy_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: